// AUTO-GENERATED by go_manager/cmd/profile2cpp
// DO NOT EDIT MANUALLY.
//
// Tool version:    1.0.0
// Source SHA256:   9080fb09ce3c4ba1cd4a5f7f5cbe9b1a83328bd6ff90776d2f968208cad65871
// Generated at:    2026-07-17 07:55:40
//
// Codegen flow:
//   1. 编辑 go_manager/profile.json
//   2. go run ./cmd/profile2cpp --input=profile.json --output=this.h
//   3. 本文件被覆盖生成
//   4. C++ Provider 引用本文件 constexpr 常量
//
// 字段映射表: Docs/仿真框架v2_字段映射表.md
// Schema 定义: go_manager/internal/profile/schema.go

#ifndef DCHROMIUM_FORK_VIRTUAL_ENVIRONMENT_PROFILE_H_
#define DCHROMIUM_FORK_VIRTUAL_ENVIRONMENT_PROFILE_H_

#include <array>
#include <cstdint>
#include <string>
#include <utility>

namespace virtual_environment {

// ==============================
// Profile ID 枚举
// ==============================
enum class ProfileId {
  kCN_OfficeIntelUHD630_Win10,
  kEN_OfficeIntelUHD630_Win10,
};

// ==============================
// CN profile 常量
// ==============================
namespace cn {

// Hardware
inline constexpr int kCpuCores = 0;
inline constexpr int kCpuThreads = 0;
inline constexpr const char* kCpuModel = "";
inline constexpr const char* kCpuArchitecture = "";
inline constexpr int kMemoryMB = 0;

inline constexpr const char* kGpuVendor = "";
inline constexpr const char* kGpuModel = "";
inline constexpr const char* kGpuDriverVersion = "";
inline constexpr int kGpuVramMB = 0;
inline constexpr bool kGpuIsSoftware = false;
inline constexpr bool kGpuIsHybrid = false;

// System
inline constexpr const char* kOsString = "";
inline constexpr const char* kPlatformString = "";
inline constexpr const char* kOsVersion = "";
inline constexpr const char* kOsBuild = "";

// Locale
inline constexpr const char* kLanguage = "";
inline constexpr const char* kTimezone = "";
inline constexpr int kTimezoneOffsetMinutes = 0;

// Screen
inline constexpr int kScreenWidthPx = 0;
inline constexpr int kScreenHeightPx = 0;
inline constexpr int kScreenColorDepth = 0;
inline constexpr float kScreenDPR = 0;

// WebGL
inline constexpr const char* kWebglRenderer = "";
inline constexpr const char* kWebglVendor = "";
inline constexpr const char* kWebglVersion = "";
inline constexpr const char* kWebglShadingLanguageVersion = "";
inline constexpr int kWebglMaxTextureSize = 0;
inline constexpr int kWebglMaxCombinedTextureImageUnits = 0;
inline constexpr int kWebglMaxCubeMapTextureSize = 0;
inline constexpr int kWebglMaxFragmentUniformVectors = 0;
inline constexpr int kWebglMaxVertexUniformVectors = 0;
inline constexpr int kWebglMaxVaryingVectors = 0;

// Emoji
inline constexpr const char* kEmojiDescription = "";

}  // namespace cn

// ==============================
// EN profile 常量（结构同上）
// ==============================
namespace en {

// Hardware
inline constexpr int kCpuCores = 0;
inline constexpr int kCpuThreads = 0;
inline constexpr const char* kCpuModel = "";
inline constexpr const char* kCpuArchitecture = "";
inline constexpr int kMemoryMB = 0;

inline constexpr const char* kGpuVendor = "";
inline constexpr const char* kGpuModel = "";
inline constexpr const char* kGpuDriverVersion = "";
inline constexpr int kGpuVramMB = 0;
inline constexpr bool kGpuIsSoftware = false;
inline constexpr bool kGpuIsHybrid = false;

// System
inline constexpr const char* kOsString = "";
inline constexpr const char* kPlatformString = "";
inline constexpr const char* kOsVersion = "";
inline constexpr const char* kOsBuild = "";

// Locale
inline constexpr const char* kLanguage = "";
inline constexpr const char* kTimezone = "";
inline constexpr int kTimezoneOffsetMinutes = 0;

// Screen
inline constexpr int kScreenWidthPx = 0;
inline constexpr int kScreenHeightPx = 0;
inline constexpr int kScreenColorDepth = 0;
inline constexpr float kScreenDPR = 0;

// WebGL
inline constexpr const char* kWebglRenderer = "";
inline constexpr const char* kWebglVendor = "";
inline constexpr const char* kWebglVersion = "";
inline constexpr const char* kWebglShadingLanguageVersion = "";
inline constexpr int kWebglMaxTextureSize = 0;

// Emoji
inline constexpr const char* kEmojiDescription = "";

}  // namespace en

}  // namespace virtual_environment

#endif  // DCHROMIUM_FORK_VIRTUAL_ENVIRONMENT_PROFILE_H_
